# Generated by Django 3.2.3 on 2021-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210530_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
